export const permissions = [
  {
    name: 'users',
    actions: {
      index: true,
      create: true,
      show: true,
      edit: true,
      delete: true,
      export: true,
    },
  },
  {
    name: 'roles',
    actions: {
      index: true,
      create: true,
      show: true,
      edit: true,
      delete: true,
      export: true,
    },
  },
  {
    name: 'nha',
    actions: {
      index: true,
      create: true,
      show: true,
      edit: true,
      delete: true,
      export: true,
    },
  },
  {
    name: 'loai-nha-tro',
    actions: {
      index: true,
      create: true,
      show: true,
      edit: true,
      delete: true,
      export: true,
    },
  },
  {
    name: 'tinh',
    actions: {
      index: true,
      create: true,
      show: true,
      edit: true,
      delete: true,
      export: true,
    },
  },
  {
    name: 'huyen',
    actions: {
      index: true,
      create: true,
      show: true,
      edit: true,
      delete: true,
      export: true,
    },
  },
  {
    name: 'xa',
    actions: {
      index: true,
      create: true,
      show: true,
      edit: true,
      delete: true,
      export: true,
    },
  },
  {
    name: 'phong',
    actions: {
      index: true,
      create: true,
      show: true,
      edit: true,
      delete: true,
      export: true,
    },
  },
  {
    name: 'nhom-phong-nha',
    actions: {
      index: true,
      create: true,
      show: true,
      edit: true,
      delete: true,
      export: true,
    },
  },
  {
    name: 'hop-dong',
    actions: {
      index: true,
      create: true,
      show: true,
      edit: true,
      delete: true,
      export: true,
    },
  },
  {
    name: 'mau-hop-dong',
    actions: {
      index: true,
      create: true,
      show: true,
      edit: true,
      delete: true,
      export: true,
    },
  },
  {
    name: 'hoa-don',
    actions: {
      index: true,
      create: true,
      show: true,
      edit: true,
      delete: true,
      export: true,
    },
  },
  {
    name: 'dich-vu',
    actions: {
      index: true,
      create: true,
      show: true,
      edit: true,
      delete: true,
      export: true,
    },
  },
  {
    name: 'phong-dich-vu',
    actions: {
      index: true,
      create: true,
      show: true,
      edit: true,
      delete: true,
      export: true,
    },
  },
  {
    name: 'dich-vu-dinh-muc',
    actions: {
      index: true,
      create: true,
      show: true,
      edit: true,
      delete: true,
      export: true,
    },
  },
  {
    name: 'mau-phieu',
    actions: {
      index: true,
      create: true,
      show: true,
      edit: true,
      delete: true,
      export: true,
    },
  },
  {
    name: 'mau-hop-dong',
    actions: {
      index: true,
      create: true,
      show: true,
      edit: true,
      delete: true,
      export: true,
    },
  },
  {
    name: 'mau-phieu-ap-dung',
    actions: {
      index: true,
      create: true,
      show: true,
      edit: true,
      delete: true,
      export: true,
    },
  },
  {
    name: 'mau-hop-dong-ap-dung',
    actions: {
      index: true,
      create: true,
      show: true,
      edit: true,
      delete: true,
      export: true,
    },
  },
  {
    name: 'giao-dich',
    actions: {
      index: true,
      create: true,
      show: true,
      edit: true,
      delete: true,
      export: true,
    },
  },
  {
    name: 'chi-tiet-giao-dich',
    actions: {
      index: true,
      create: true,
      show: true,
      edit: true,
      delete: true,
      export: true,
    },
  },
  {
    name: 'ly-do',
    actions: {
      index: true,
      create: true,
      show: true,
      edit: true,
      delete: true,
      export: true,
    },
  },
  {
    name: 'khach-thue',
    actions: {
      index: true,
      create: true,
      show: true,
      edit: true,
      delete: true,
      export: true,
    },
  },
  {
    name: 'phong-su-dung-dich-vu',
    actions: {
      index: true,
      create: true,
      show: true,
      edit: true,
      delete: true,
      export: true,
    },
  },
  {
    name: 'cau-hinh-nha',
    actions: {
      index: true,
      create: true,
      show: true,
      edit: true,
      delete: true,
      export: true,
    },
  },
  {
    name: 'ngan-hang',
    actions: {
      index: true,
      create: true,
      show: true,
      edit: true,
      delete: true,
      export: true,
    },
  },
  {
    name: 'chu-tro',
    actions: {
      index: true,
      create: true,
      show: true,
      edit: true,
      delete: true,
      export: true,
    },
  },
  {
    name: 'nguoi-o-phong',
    actions: {
      index: true,
      create: true,
      show: true,
      edit: true,
      delete: true,
      export: true,
    },
  },
  {
    name: 'mau-hoa-don',
    actions: {
      index: true,
      create: true,
      show: true,
      edit: true,
      delete: true,
      export: true,
    },
  },
  {
    name: 'tien-ich-nha',
    actions: {
      index: true,
      create: true,
      show: true,
      edit: true,
      delete: true,
      export: true,
    },
  },
  {
    name: 'tien-ich',
    actions: {
      index: true,
      create: true,
      show: true,
      edit: true,
      delete: true,
      export: true,
    },
  },
  {
    name: 'noi-quy',
    actions: {
      index: true,
      create: true,
      show: true,
      edit: true,
      delete: true,
      export: true,
    },
  },
  {
    name: 'noi-quy-nha',
    actions: {
      index: true,
      create: true,
      show: true,
      edit: true,
      delete: true,
      export: true,
    },
  },
  {
    name: 'don-vi-tinh',
    actions: {
      index: true,
      create: true,
      show: true,
      edit: true,
      delete: true,
      export: true,
    },
  },
  {
    name: 'report-chu-tro',
    actions: {
      index: true,
      create: true,
      show: true,
      edit: true,
      delete: true,
      export: true,
    },
  },
  {
    name: 'report-khach-thue',
    actions: {
      index: true,
      create: true,
      show: true,
      edit: true,
      delete: true,
      export: true,
    },
  },
  /*IMPORT_OTHER_PERMISSON_HERE*/
];
